import { Provider } from 'react-redux'
import Navbar from '../components/Navbar'
import '../styles/globals.css'
import store from '../redux/store'
import Head from 'next/head'
import { AppProps } from 'next/app'

function MyApp({ Component, pageProps }:AppProps) {
    return (
        <>
            <Head>
                <title>IPL Table!!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Provider store={store}>
                <Navbar />
                <Component {...pageProps} />
            </Provider>
        </>
    )
}

export default MyApp